"use client";

import {
  BarChart3,
  Box,
  Brain,
  Cloud,
  Code,
  Cpu,
  Database,
  Gamepad2,
  Globe,
  Layers,
  Lock,
  Package,
  Palette,
  Rocket,
  Server,
  Shield,
  Sparkles,
  Terminal,
  Wifi,
  Zap,
  type LucideIcon,
} from "lucide-react";
import type { ComponentType } from "react";
import {
  SiAndroid,
  SiAngular,
  SiApple,
  SiAstro,
  SiBootstrap,
  SiBun,
  SiC,
  SiCloudflare,
  SiCplusplus,
  SiSharp,
  SiCss,
  SiDart,
  SiDeno,
  SiDjango,
  SiDocker,
  SiDotnet,
  SiElectron,
  SiElixir,
  SiFigma,
  SiFirebase,
  SiFlask,
  SiFlutter,
  SiFortran,
  SiGit,
  SiGithub,
  SiGitlab,
  SiGo,
  SiGodotengine,
  SiGooglecloud,
  SiGrafana,
  SiGraphql,
  SiHaskell,
  SiHtml5,
  SiJavascript,
  SiJenkins,
  SiJupyter,
  SiKotlin,
  SiKubernetes,
  SiLinux,
  SiLua,
  SiMongodb,
  SiMysql,
  SiNestjs,
  SiNetlify,
  SiNextdotjs,
  SiNginx,
  SiNodedotjs,
  SiNotion,
  SiNuxt,
  SiNvidia,
  SiOpenai,
  SiOpencv,
  SiPerl,
  SiPhp,
  SiPostgresql,
  SiPrisma,
  SiPython,
  SiPytorch,
  SiR,
  SiReact,
  SiRedis,
  SiRuby,
  SiRust,
  SiSass,
  SiScala,
  SiSolidity,
  SiSqlite,
  SiSupabase,
  SiSvelte,
  SiSwift,
  SiTailwindcss,
  SiTensorflow,
  SiTerraform,
  SiTypescript,
  SiUnity,
  SiUnrealengine,
  SiVercel,
  SiVscodium,
  SiVuedotjs,
  SiWebgl,
  SiZig,
} from "react-icons/si";

export type BatchCardIconKind = "brand" | "lucide";

export type ResolvedBatchCardIcon = {
  key: string;
  Icon: ComponentType<{ className?: string; strokeWidth?: number }> | LucideIcon;
  kind: BatchCardIconKind;
};

type RegistryEntry = {
  Icon: ComponentType<{ className?: string; strokeWidth?: number }> | LucideIcon;
  kind: BatchCardIconKind;
};

const REGISTRY: Record<string, RegistryEntry> = {
  /* ---- Simple Icons ---- */
  "si-android": { Icon: SiAndroid, kind: "brand" },
  "si-angular": { Icon: SiAngular, kind: "brand" },
  "si-apple": { Icon: SiApple, kind: "brand" },
  "si-astro": { Icon: SiAstro, kind: "brand" },
  "si-bootstrap": { Icon: SiBootstrap, kind: "brand" },
  "si-bun": { Icon: SiBun, kind: "brand" },
  "si-c": { Icon: SiC, kind: "brand" },
  "si-cloudflare": { Icon: SiCloudflare, kind: "brand" },
  "si-cplusplus": { Icon: SiCplusplus, kind: "brand" },
  "si-csharp": { Icon: SiSharp, kind: "brand" },
  "si-css3": { Icon: SiCss, kind: "brand" },
  "si-dart": { Icon: SiDart, kind: "brand" },
  "si-deno": { Icon: SiDeno, kind: "brand" },
  "si-django": { Icon: SiDjango, kind: "brand" },
  "si-docker": { Icon: SiDocker, kind: "brand" },
  "si-dotnet": { Icon: SiDotnet, kind: "brand" },
  "si-electron": { Icon: SiElectron, kind: "brand" },
  "si-elixir": { Icon: SiElixir, kind: "brand" },
  "si-figma": { Icon: SiFigma, kind: "brand" },
  "si-firebase": { Icon: SiFirebase, kind: "brand" },
  "si-flask": { Icon: SiFlask, kind: "brand" },
  "si-flutter": { Icon: SiFlutter, kind: "brand" },
  "si-fortran": { Icon: SiFortran, kind: "brand" },
  "si-git": { Icon: SiGit, kind: "brand" },
  "si-github": { Icon: SiGithub, kind: "brand" },
  "si-gitlab": { Icon: SiGitlab, kind: "brand" },
  "si-go": { Icon: SiGo, kind: "brand" },
  "si-godotengine": { Icon: SiGodotengine, kind: "brand" },
  "si-googlecloud": { Icon: SiGooglecloud, kind: "brand" },
  "si-grafana": { Icon: SiGrafana, kind: "brand" },
  "si-graphql": { Icon: SiGraphql, kind: "brand" },
  "si-haskell": { Icon: SiHaskell, kind: "brand" },
  "si-html5": { Icon: SiHtml5, kind: "brand" },
  "si-javascript": { Icon: SiJavascript, kind: "brand" },
  "si-jenkins": { Icon: SiJenkins, kind: "brand" },
  "si-jupyter": { Icon: SiJupyter, kind: "brand" },
  "si-kotlin": { Icon: SiKotlin, kind: "brand" },
  "si-kubernetes": { Icon: SiKubernetes, kind: "brand" },
  "si-linux": { Icon: SiLinux, kind: "brand" },
  "si-lua": { Icon: SiLua, kind: "brand" },
  "si-mongodb": { Icon: SiMongodb, kind: "brand" },
  "si-mysql": { Icon: SiMysql, kind: "brand" },
  "si-nestjs": { Icon: SiNestjs, kind: "brand" },
  "si-netlify": { Icon: SiNetlify, kind: "brand" },
  "si-nextdotjs": { Icon: SiNextdotjs, kind: "brand" },
  "si-nginx": { Icon: SiNginx, kind: "brand" },
  "si-nodedotjs": { Icon: SiNodedotjs, kind: "brand" },
  "si-notion": { Icon: SiNotion, kind: "brand" },
  "si-nuxtdotjs": { Icon: SiNuxt, kind: "brand" },
  "si-nvidia": { Icon: SiNvidia, kind: "brand" },
  "si-openai": { Icon: SiOpenai, kind: "brand" },
  "si-opencv": { Icon: SiOpencv, kind: "brand" },
  "si-perl": { Icon: SiPerl, kind: "brand" },
  "si-php": { Icon: SiPhp, kind: "brand" },
  "si-postgresql": { Icon: SiPostgresql, kind: "brand" },
  "si-prisma": { Icon: SiPrisma, kind: "brand" },
  "si-python": { Icon: SiPython, kind: "brand" },
  "si-pytorch": { Icon: SiPytorch, kind: "brand" },
  "si-r": { Icon: SiR, kind: "brand" },
  "si-react": { Icon: SiReact, kind: "brand" },
  "si-redis": { Icon: SiRedis, kind: "brand" },
  "si-ruby": { Icon: SiRuby, kind: "brand" },
  "si-rust": { Icon: SiRust, kind: "brand" },
  "si-sass": { Icon: SiSass, kind: "brand" },
  "si-scala": { Icon: SiScala, kind: "brand" },
  "si-solidity": { Icon: SiSolidity, kind: "brand" },
  "si-sqlite": { Icon: SiSqlite, kind: "brand" },
  "si-supabase": { Icon: SiSupabase, kind: "brand" },
  "si-svelte": { Icon: SiSvelte, kind: "brand" },
  "si-swift": { Icon: SiSwift, kind: "brand" },
  "si-tailwindcss": { Icon: SiTailwindcss, kind: "brand" },
  "si-tensorflow": { Icon: SiTensorflow, kind: "brand" },
  "si-terraform": { Icon: SiTerraform, kind: "brand" },
  "si-typescript": { Icon: SiTypescript, kind: "brand" },
  "si-unity": { Icon: SiUnity, kind: "brand" },
  "si-unrealengine": { Icon: SiUnrealengine, kind: "brand" },
  "si-vercel": { Icon: SiVercel, kind: "brand" },
  "si-vscodium": { Icon: SiVscodium, kind: "brand" },
  "si-vuedotjs": { Icon: SiVuedotjs, kind: "brand" },
  "si-webgl": { Icon: SiWebgl, kind: "brand" },
  "si-zig": { Icon: SiZig, kind: "brand" },

  /* ---- Lucide ---- */
  "lucide-bar-chart-3": { Icon: BarChart3, kind: "lucide" },
  "lucide-box": { Icon: Box, kind: "lucide" },
  "lucide-brain": { Icon: Brain, kind: "lucide" },
  "lucide-cloud": { Icon: Cloud, kind: "lucide" },
  "lucide-code": { Icon: Code, kind: "lucide" },
  "lucide-cpu": { Icon: Cpu, kind: "lucide" },
  "lucide-database": { Icon: Database, kind: "lucide" },
  "lucide-gamepad-2": { Icon: Gamepad2, kind: "lucide" },
  "lucide-globe": { Icon: Globe, kind: "lucide" },
  "lucide-layers": { Icon: Layers, kind: "lucide" },
  "lucide-lock": { Icon: Lock, kind: "lucide" },
  "lucide-package": { Icon: Package, kind: "lucide" },
  "lucide-palette": { Icon: Palette, kind: "lucide" },
  "lucide-rocket": { Icon: Rocket, kind: "lucide" },
  "lucide-server": { Icon: Server, kind: "lucide" },
  "lucide-shield": { Icon: Shield, kind: "lucide" },
  "lucide-sparkles": { Icon: Sparkles, kind: "lucide" },
  "lucide-terminal": { Icon: Terminal, kind: "lucide" },
  "lucide-wifi": { Icon: Wifi, kind: "lucide" },
  "lucide-zap": { Icon: Zap, kind: "lucide" },
};

export function resolveBatchCardIcons(keys: string[]): ResolvedBatchCardIcon[] {
  const out: ResolvedBatchCardIcon[] = [];
  for (const raw of keys) {
    const key = raw.trim().toLowerCase();
    const entry = REGISTRY[key];
    if (entry) {
      out.push({ key, Icon: entry.Icon, kind: entry.kind });
    }
  }
  return out;
}
