"use client";

import {
  Activity,
  Atom,
  Award,
  BarChart3,
  BookOpen,
  Box,
  Brain,
  Briefcase,
  Camera,
  Cloud,
  Code,
  Compass,
  Cpu,
  Database,
  DollarSign,
  Film,
  Flag,
  Flame,
  Gamepad2,
  Globe,
  GraduationCap,
  Headphones,
  Heart,
  Image,
  Layers,
  Lightbulb,
  Lock,
  Mail,
  Megaphone,
  MessageSquare,
  Mic,
  Microscope,
  Monitor,
  Music,
  Package,
  Paintbrush,
  Palette,
  PenTool,
  PieChart,
  Rocket,
  Server,
  Shield,
  Smartphone,
  Sparkles,
  Star,
  Target,
  Terminal,
  TestTube,
  TrendingUp,
  Trophy,
  Users,
  Wifi,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";
import type { ComponentType } from "react";
import {
  SiAndroid,
  SiAngular,
  SiAnsible,
  SiApachekafka,
  SiApple,
  SiArchlinux,
  SiArduino,
  SiAstro,
  SiBlender,
  SiBootstrap,
  SiBun,
  SiC,
  SiCanva,
  SiCloudflare,
  SiConfluence,
  SiCplusplus,
  SiSharp,
  SiCss,
  SiDart,
  SiDeno,
  SiDigitalocean,
  SiDiscord,
  SiDjango,
  SiDocker,
  SiDotnet,
  SiElastic,
  SiElectron,
  SiElixir,
  SiEthereum,
  SiExpress,
  SiFigma,
  SiFirebase,
  SiFlask,
  SiFlutter,
  SiFortran,
  SiGit,
  SiGithub,
  SiGitlab,
  SiGnubash,
  SiGo,
  SiGodotengine,
  SiGooglecloud,
  SiGrafana,
  SiGraphql,
  SiHaskell,
  SiHelm,
  SiHeroku,
  SiHtml5,
  SiJavascript,
  SiJenkins,
  SiJira,
  SiJupyter,
  SiKotlin,
  SiKubernetes,
  SiLaravel,
  SiLatex,
  SiLinux,
  SiLua,
  SiMarkdown,
  SiMongodb,
  SiMysql,
  SiNestjs,
  SiNeovim,
  SiNetlify,
  SiNextdotjs,
  SiNginx,
  SiNodedotjs,
  SiNotion,
  SiNumpy,
  SiNuxt,
  SiNvidia,
  SiOpenai,
  SiOpencv,
  SiPandas,
  SiPerl,
  SiPhp,
  SiPostgresql,
  SiPostman,
  SiPrisma,
  SiPrometheus,
  SiPython,
  SiPytorch,
  SiR,
  SiRabbitmq,
  SiRaspberrypi,
  SiReact,
  SiRedis,
  SiRuby,
  SiRust,
  SiSass,
  SiScala,
  SiShopify,
  SiSlack,
  SiSnowflake,
  SiSolidity,
  SiSpring,
  SiSpringboot,
  SiSqlite,
  SiStripe,
  SiSupabase,
  SiSvelte,
  SiSwift,
  SiTailwindcss,
  SiTensorflow,
  SiTerraform,
  SiThreedotjs,
  SiTypescript,
  SiUbuntu,
  SiUnity,
  SiUnrealengine,
  SiVercel,
  SiVim,
  SiVscodium,
  SiVuedotjs,
  SiWebassembly,
  SiWebgl,
  SiWordpress,
  SiZig,
} from "react-icons/si";

export type BatchCardIconKind = "brand" | "lucide";

export type ResolvedBatchCardIcon = {
  key: string;
  Icon: ComponentType<{ className?: string; strokeWidth?: number }> | LucideIcon;
  kind: BatchCardIconKind;
};

type RegistryEntry = {
  Icon: ComponentType<{ className?: string; strokeWidth?: number }> | LucideIcon;
  kind: BatchCardIconKind;
};

const REGISTRY: Record<string, RegistryEntry> = {
  /* ---- Simple Icons ---- */
  "si-android": { Icon: SiAndroid, kind: "brand" },
  "si-angular": { Icon: SiAngular, kind: "brand" },
  "si-ansible": { Icon: SiAnsible, kind: "brand" },
  "si-apachekafka": { Icon: SiApachekafka, kind: "brand" },
  "si-apple": { Icon: SiApple, kind: "brand" },
  "si-archlinux": { Icon: SiArchlinux, kind: "brand" },
  "si-arduino": { Icon: SiArduino, kind: "brand" },
  "si-astro": { Icon: SiAstro, kind: "brand" },
  "si-blender": { Icon: SiBlender, kind: "brand" },
  "si-bootstrap": { Icon: SiBootstrap, kind: "brand" },
  "si-bun": { Icon: SiBun, kind: "brand" },
  "si-c": { Icon: SiC, kind: "brand" },
  "si-canva": { Icon: SiCanva, kind: "brand" },
  "si-cloudflare": { Icon: SiCloudflare, kind: "brand" },
  "si-confluence": { Icon: SiConfluence, kind: "brand" },
  "si-cplusplus": { Icon: SiCplusplus, kind: "brand" },
  "si-csharp": { Icon: SiSharp, kind: "brand" },
  "si-css3": { Icon: SiCss, kind: "brand" },
  "si-dart": { Icon: SiDart, kind: "brand" },
  "si-deno": { Icon: SiDeno, kind: "brand" },
  "si-digitalocean": { Icon: SiDigitalocean, kind: "brand" },
  "si-discord": { Icon: SiDiscord, kind: "brand" },
  "si-django": { Icon: SiDjango, kind: "brand" },
  "si-docker": { Icon: SiDocker, kind: "brand" },
  "si-dotnet": { Icon: SiDotnet, kind: "brand" },
  "si-elastic": { Icon: SiElastic, kind: "brand" },
  "si-electron": { Icon: SiElectron, kind: "brand" },
  "si-elixir": { Icon: SiElixir, kind: "brand" },
  "si-ethereum": { Icon: SiEthereum, kind: "brand" },
  "si-express": { Icon: SiExpress, kind: "brand" },
  "si-figma": { Icon: SiFigma, kind: "brand" },
  "si-firebase": { Icon: SiFirebase, kind: "brand" },
  "si-flask": { Icon: SiFlask, kind: "brand" },
  "si-flutter": { Icon: SiFlutter, kind: "brand" },
  "si-fortran": { Icon: SiFortran, kind: "brand" },
  "si-git": { Icon: SiGit, kind: "brand" },
  "si-github": { Icon: SiGithub, kind: "brand" },
  "si-gitlab": { Icon: SiGitlab, kind: "brand" },
  "si-gnubash": { Icon: SiGnubash, kind: "brand" },
  "si-go": { Icon: SiGo, kind: "brand" },
  "si-godotengine": { Icon: SiGodotengine, kind: "brand" },
  "si-googlecloud": { Icon: SiGooglecloud, kind: "brand" },
  "si-grafana": { Icon: SiGrafana, kind: "brand" },
  "si-graphql": { Icon: SiGraphql, kind: "brand" },
  "si-haskell": { Icon: SiHaskell, kind: "brand" },
  "si-helm": { Icon: SiHelm, kind: "brand" },
  "si-heroku": { Icon: SiHeroku, kind: "brand" },
  "si-html5": { Icon: SiHtml5, kind: "brand" },
  "si-javascript": { Icon: SiJavascript, kind: "brand" },
  "si-jenkins": { Icon: SiJenkins, kind: "brand" },
  "si-jira": { Icon: SiJira, kind: "brand" },
  "si-jupyter": { Icon: SiJupyter, kind: "brand" },
  "si-kotlin": { Icon: SiKotlin, kind: "brand" },
  "si-kubernetes": { Icon: SiKubernetes, kind: "brand" },
  "si-laravel": { Icon: SiLaravel, kind: "brand" },
  "si-latex": { Icon: SiLatex, kind: "brand" },
  "si-linux": { Icon: SiLinux, kind: "brand" },
  "si-lua": { Icon: SiLua, kind: "brand" },
  "si-markdown": { Icon: SiMarkdown, kind: "brand" },
  "si-mongodb": { Icon: SiMongodb, kind: "brand" },
  "si-mysql": { Icon: SiMysql, kind: "brand" },
  "si-nestjs": { Icon: SiNestjs, kind: "brand" },
  "si-neovim": { Icon: SiNeovim, kind: "brand" },
  "si-netlify": { Icon: SiNetlify, kind: "brand" },
  "si-nextdotjs": { Icon: SiNextdotjs, kind: "brand" },
  "si-nginx": { Icon: SiNginx, kind: "brand" },
  "si-nodedotjs": { Icon: SiNodedotjs, kind: "brand" },
  "si-notion": { Icon: SiNotion, kind: "brand" },
  "si-numpy": { Icon: SiNumpy, kind: "brand" },
  "si-nuxtdotjs": { Icon: SiNuxt, kind: "brand" },
  "si-nvidia": { Icon: SiNvidia, kind: "brand" },
  "si-openai": { Icon: SiOpenai, kind: "brand" },
  "si-opencv": { Icon: SiOpencv, kind: "brand" },
  "si-pandas": { Icon: SiPandas, kind: "brand" },
  "si-perl": { Icon: SiPerl, kind: "brand" },
  "si-php": { Icon: SiPhp, kind: "brand" },
  "si-postgresql": { Icon: SiPostgresql, kind: "brand" },
  "si-postman": { Icon: SiPostman, kind: "brand" },
  "si-prisma": { Icon: SiPrisma, kind: "brand" },
  "si-prometheus": { Icon: SiPrometheus, kind: "brand" },
  "si-python": { Icon: SiPython, kind: "brand" },
  "si-pytorch": { Icon: SiPytorch, kind: "brand" },
  "si-r": { Icon: SiR, kind: "brand" },
  "si-rabbitmq": { Icon: SiRabbitmq, kind: "brand" },
  "si-raspberrypi": { Icon: SiRaspberrypi, kind: "brand" },
  "si-react": { Icon: SiReact, kind: "brand" },
  "si-redis": { Icon: SiRedis, kind: "brand" },
  "si-ruby": { Icon: SiRuby, kind: "brand" },
  "si-rust": { Icon: SiRust, kind: "brand" },
  "si-sass": { Icon: SiSass, kind: "brand" },
  "si-scala": { Icon: SiScala, kind: "brand" },
  "si-shopify": { Icon: SiShopify, kind: "brand" },
  "si-slack": { Icon: SiSlack, kind: "brand" },
  "si-snowflake": { Icon: SiSnowflake, kind: "brand" },
  "si-solidity": { Icon: SiSolidity, kind: "brand" },
  "si-spring": { Icon: SiSpring, kind: "brand" },
  "si-springboot": { Icon: SiSpringboot, kind: "brand" },
  "si-sqlite": { Icon: SiSqlite, kind: "brand" },
  "si-stripe": { Icon: SiStripe, kind: "brand" },
  "si-supabase": { Icon: SiSupabase, kind: "brand" },
  "si-svelte": { Icon: SiSvelte, kind: "brand" },
  "si-swift": { Icon: SiSwift, kind: "brand" },
  "si-tailwindcss": { Icon: SiTailwindcss, kind: "brand" },
  "si-tensorflow": { Icon: SiTensorflow, kind: "brand" },
  "si-terraform": { Icon: SiTerraform, kind: "brand" },
  "si-threedotjs": { Icon: SiThreedotjs, kind: "brand" },
  "si-typescript": { Icon: SiTypescript, kind: "brand" },
  "si-ubuntu": { Icon: SiUbuntu, kind: "brand" },
  "si-unity": { Icon: SiUnity, kind: "brand" },
  "si-unrealengine": { Icon: SiUnrealengine, kind: "brand" },
  "si-vercel": { Icon: SiVercel, kind: "brand" },
  "si-vim": { Icon: SiVim, kind: "brand" },
  "si-vscodium": { Icon: SiVscodium, kind: "brand" },
  "si-vuedotjs": { Icon: SiVuedotjs, kind: "brand" },
  "si-webassembly": { Icon: SiWebassembly, kind: "brand" },
  "si-webgl": { Icon: SiWebgl, kind: "brand" },
  "si-wordpress": { Icon: SiWordpress, kind: "brand" },
  "si-zig": { Icon: SiZig, kind: "brand" },

  /* ---- Lucide ---- */
  "lucide-activity": { Icon: Activity, kind: "lucide" },
  "lucide-atom": { Icon: Atom, kind: "lucide" },
  "lucide-award": { Icon: Award, kind: "lucide" },
  "lucide-bar-chart-3": { Icon: BarChart3, kind: "lucide" },
  "lucide-book-open": { Icon: BookOpen, kind: "lucide" },
  "lucide-box": { Icon: Box, kind: "lucide" },
  "lucide-brain": { Icon: Brain, kind: "lucide" },
  "lucide-briefcase": { Icon: Briefcase, kind: "lucide" },
  "lucide-camera": { Icon: Camera, kind: "lucide" },
  "lucide-cloud": { Icon: Cloud, kind: "lucide" },
  "lucide-code": { Icon: Code, kind: "lucide" },
  "lucide-compass": { Icon: Compass, kind: "lucide" },
  "lucide-cpu": { Icon: Cpu, kind: "lucide" },
  "lucide-database": { Icon: Database, kind: "lucide" },
  "lucide-dollar-sign": { Icon: DollarSign, kind: "lucide" },
  "lucide-film": { Icon: Film, kind: "lucide" },
  "lucide-flag": { Icon: Flag, kind: "lucide" },
  "lucide-flame": { Icon: Flame, kind: "lucide" },
  "lucide-gamepad-2": { Icon: Gamepad2, kind: "lucide" },
  "lucide-globe": { Icon: Globe, kind: "lucide" },
  "lucide-graduation-cap": { Icon: GraduationCap, kind: "lucide" },
  "lucide-headphones": { Icon: Headphones, kind: "lucide" },
  "lucide-heart": { Icon: Heart, kind: "lucide" },
  "lucide-image": { Icon: Image, kind: "lucide" },
  "lucide-layers": { Icon: Layers, kind: "lucide" },
  "lucide-lightbulb": { Icon: Lightbulb, kind: "lucide" },
  "lucide-lock": { Icon: Lock, kind: "lucide" },
  "lucide-mail": { Icon: Mail, kind: "lucide" },
  "lucide-megaphone": { Icon: Megaphone, kind: "lucide" },
  "lucide-message-square": { Icon: MessageSquare, kind: "lucide" },
  "lucide-mic": { Icon: Mic, kind: "lucide" },
  "lucide-microscope": { Icon: Microscope, kind: "lucide" },
  "lucide-monitor": { Icon: Monitor, kind: "lucide" },
  "lucide-music": { Icon: Music, kind: "lucide" },
  "lucide-package": { Icon: Package, kind: "lucide" },
  "lucide-paintbrush": { Icon: Paintbrush, kind: "lucide" },
  "lucide-palette": { Icon: Palette, kind: "lucide" },
  "lucide-pen-tool": { Icon: PenTool, kind: "lucide" },
  "lucide-pie-chart": { Icon: PieChart, kind: "lucide" },
  "lucide-rocket": { Icon: Rocket, kind: "lucide" },
  "lucide-server": { Icon: Server, kind: "lucide" },
  "lucide-shield": { Icon: Shield, kind: "lucide" },
  "lucide-smartphone": { Icon: Smartphone, kind: "lucide" },
  "lucide-sparkles": { Icon: Sparkles, kind: "lucide" },
  "lucide-star": { Icon: Star, kind: "lucide" },
  "lucide-target": { Icon: Target, kind: "lucide" },
  "lucide-terminal": { Icon: Terminal, kind: "lucide" },
  "lucide-test-tube": { Icon: TestTube, kind: "lucide" },
  "lucide-trending-up": { Icon: TrendingUp, kind: "lucide" },
  "lucide-trophy": { Icon: Trophy, kind: "lucide" },
  "lucide-users": { Icon: Users, kind: "lucide" },
  "lucide-wifi": { Icon: Wifi, kind: "lucide" },
  "lucide-wrench": { Icon: Wrench, kind: "lucide" },
  "lucide-zap": { Icon: Zap, kind: "lucide" },
};

export function resolveBatchCardIcons(keys: string[]): ResolvedBatchCardIcon[] {
  const out: ResolvedBatchCardIcon[] = [];
  for (const raw of keys) {
    const key = raw.trim().toLowerCase();
    const entry = REGISTRY[key];
    if (entry) {
      out.push({ key, Icon: entry.Icon, kind: entry.kind });
    }
  }
  return out;
}
